# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"


[plugins]


[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.completions]
github = "zsh-users/zsh-completions"

# [plugins.docker-zsh-completion]
# github = "greymd/docker-zsh-completion"

# [plugins.rust-zsh-completions]
# github = "ryutok/rust-zsh-completions"

[plugins.ohmyzsh-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["{clipboard,completion,git,key-bindings,termsupport,theme-and-appearance}.zsh"]
apply = ["defer"]

[plugins.ohmyzsh-plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["{copybuffer,git,direnv,pip,fzf,command-not-found}/*.plugin.zsh"]
apply = ["defer"]

[plugins.fzftab]
github = "Aloxaf/fzf-tab"
apply = ["defer"]

[plugins.fzfmarks]
github = "urbainvaes/fzf-marks"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ["defer"]

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"

[plugins.asdf]
github = "asdf-vm/asdf"

[plugins.set-java-home]
local = "~/.asdf/plugins/java"
apply = ["defer"]

